name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install libssl-dev libcurl4-openssl-dev
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        pip install pylint black
    - name: Python Code Quality and Lint
      # You may pin to the exact commit or the version.
      # uses: ricardochaves/python-lint@32032eca67291cd71f88d79e61bc4b904ee03265
      uses: ricardochaves/python-lint@v1.3.0
      with:
        # A list of all paths to test
        python-root-list: . # optional, default is .
        # Use Pylint
        use-pylint: true # optional, default is true
        # Use pycodestyle
        use-pycodestyle: false # optional, default is true
        # Use Flake8
        use-flake8: false # optional, default is true
        # Use Black
        use-black: true # optional, default is true
        # Use mypy
        use-mypy: false # optional, default is true
        # Use isort
        use-isort: false # optional, default is true
        # Extra options: pylint $(extra-pylint-options) $(python-root-list)
        extra-pylint-options: --const-rgx='[a-z\_][a-z0-9\_]{2,30}$' # optional, default is 
        # Extra options: black --check $(extra-black-options) $(python-root-list)
        extra-black-options: -l 111 -t py37 # optional, default is 
